<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class BusinessRegisterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'firstname' => 'required|min:2',
            'surname' => 'required|min:2',
            'email' => 'required|email|unique:aquabe_business',
            'password' => 'required|min:4',
            'rut' => 'required|cl_rut',
            'business_name' => 'required|min:2',
            'phone' => 'required|min:7',
            'activity' => 'required',
            'employees' => 'required',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
